dydxprotocol/protocol_v1

contracts/margin/external/ERC20/ERC20Long.sol, contracts/margin/external/ERC20/ERC20LongCreator.sol, contracts/margin/external/ERC20/ERC20Position.sol, contracts/margin/external/ERC20/ERC20Short.sol, contracts/margin/external/ERC20/ERC20ShortCreator.sol, test/margin/TestCloseWithoutCounterparty.js, test/margin/external/TestERC20Long.js, test/margin/external/TestERC20Short.js
Reverts dydxprotocol/protocol#371
=> Revert "Add optional principal cap to ERC20Position"

contracts/margin/external/ERC20/ERC20Long.sol, contracts/margin/external/ERC20/ERC20Position.sol, contracts/margin/external/ERC20/ERC20Short.sol, test/margin/external/TestERC20Long.js, test/margin/external/TestERC20Short.js
=> Allow partial closing from dutch auction

package-lock.json, package.json, src/index.js
Added TestToken to be able to deploy tokens for testing the brokerage
=> added TestToken to export, changed to version 0.1.3

scripts/docker.sh
Modify the docker image to listen on all network interfaces instead of 127.0.0.1 / loopback.
=> Docker image listen on all network interfaces

package-lock.json, package.json, scripts/docker.sh
Fix the ganache-cli command on the docker build sctipt
=> Fix Docker Build

contracts/external/0x/ZeroExExchange.sol, contracts/external/0x/ZeroExProxy.sol
https://github.com/ethereum/solidity/pull/4246#issuecomment-407827738
=> fix for solidity 0.5 testing

package-lock.json, package.json
https://github.com/ethereum/solidity/pull/4246#issuecomment-407948289
=> upgrade to zeppelin-solidity 1.11

contracts/lib/TypedSignature.sol, test/helpers/Constants.js, test/lib/TestTypedSignature.js
*REQUIRES JS CHANGE ON SIGNATURE TYPES*
=> remove null prepend signature type

contracts/margin/impl/OpenWithoutCounterpartyImpl.sol, migrations/3_seeds.js, package-lock.json, package.json, src/lib/contracts.js, test/helpers/ERC20PositionHelper.js, test/helpers/MarginHelper.js
Deploy two short tokens onto the docker container complete with bucket lender, ERC20 short, and WETH
=> Deploy short tokens with bucket lender

migrations/3_seeds.js, package-lock.json, package.json, test/helpers/ERC20PositionHelper.js, test/helpers/ZeroExHelper.js
These orders can be used to mind and close the seed short tokens
=> Add seed orders for WETH

contracts/margin/external/ERC20/ERC20LongFactory.sol, contracts/margin/external/ERC20/ERC20PositionFactory.sol, contracts/margin/external/ERC20/ERC20ShortFactory.sol, contracts/margin/external/SharedLoanFactory.sol, migrations/2_deploy.js, migrations/deployed.json, migrations/deployments.md, src/lib/contracts.js, test/helpers/ERC20PositionHelper.js, test/tests/margin/external/TestERC20PositionFactory.js, test/tests/margin/external/TestERC721MarginPosition.js, test/tests/margin/external/TestPayableMarginMinter.js, test/tests/margin/external/TestSharedLoanFactory.js, test/tests/margin/external/bucketlender/TestBucketLender.js
=> Creator -> Factory

contracts/margin/external/BucketLender/BucketLender.sol, test/tests/margin/external/bucketlender/TestBucketLender.js
=> prevent locking-up when BUCKET_TIME is zero

.gitignore
This adds vim tempfiles to the `.gitignore`, so they do not create a dirty directory in `git status`.
=> Ignore Vim

test/tests/margin/external/oracle/TestMakerOracle.js
=> Add test cases for MakerOracle.

contracts/margin/external/oracle/MakerOracle.sol, test/tests/margin/external/oracle/TestMakerOracle.js
@BrendanChou wanted to let you take a look over this.
Some todos, could be in this PR or other:
=> Fix tests and implement MakerOracle.

contracts/margin/external/BucketLender/BucketLender.sol, contracts/margin/external/BucketLender/BucketLenderWithRecoveryDelay.sol, test/tests/margin/external/bucketlender/TestBucketLenderWithRecoveryDelay.js
=> add BucketLenderWithRecoveryDelay

migrations/2_deploy.js, package.json, scripts/save-deployed-addresses.js
Add addresses of external mainnet contracts
Make deploy script support multiple networks
=> Prepare for mainnet deploy

migrations/2_deploy.js
Put `grantAccess()` and `transferOwnership()` calls right after deploying the base protocol
=> streamline deploy script

migrations/3_seeds.js, package-lock.json, package.json, test/helpers/Constants.js, test/helpers/ERC20PositionHelper.js, test/helpers/MarginHelper.js, test/tests/js/TestSeeds.js
Rewrote `ERC20PositionHelper` to support creation of leveraged/short tokens.
=> Added Leveraged Tokens on Protocol Seeds

contracts/lib/AdvancedTokenInteract.sol, contracts/margin/external/BucketLender/BucketLenderProxy.sol, test/tests/margin/external/bucketlender/TestBucketLenderProxy.js
=> add BucketLenderProxy

contracts/margin/external/ERC20/ERC20PositionWithdrawer.sol, contracts/testing/TestERC20PositionWithdraw.sol, package-lock.json, package.json, test/tests/margin/external/erc20/TestERC20PositionWithdrawer.js
This is for positions with WETH as collateral (LETH, etc)
=> Add withdrawAsEth to ERC20PositionWithdrawer

contracts/margin/external/ERC20/ERC20Long.sol, package-lock.json, package.json, test/tests/margin/external/erc20/TestERC20Long.js
=> Update leveraged long symbol

package-lock.json, package.json, scripts/clean-build.js
Should reduce the size of the npm package
=>  Do not publish bytecode in build

contracts/lib/StringHelpers.sol, contracts/margin/external/ERC20/ERC20Long.sol, contracts/margin/external/ERC20/ERC20Short.sol, package-lock.json
Credit to #491 and @ElliotFriedman
Taking this one step further and just deleting the function
=> Remove unnecessary strcat function

contracts/margin/external/exchangewrappers/ZeroExV2MultiOrderExchangeWrapper.sol, test/helpers/ZeroExV2Helper.js, test/tests/margin/external/exchangewrappers/TestZeroExV2MultiOrderExchangeWrapper.js
Had to add a function because of the stack size limit
- Very low severity: Does not check for approval amount from the makerAddress.
=> Add short sanity check for maker balance

contracts/external/Maker/Other/IScdMcdMigration.sol, contracts/margin/external/exchangewrappers/SaiDaiExchangeWrapper.sol, contracts/testing/TestScdMcdMigration.sol, migrations/2_deploy.js, src/lib/contracts.js, test/tests/margin/external/exchangewrappers/TestSaiDaiExchangeWrapper.js
TODO: add this contract to the exchange-wrappers repo after merging it here
=> Add SAI->DAI ExchangeWrapper
